"""Tabelas esportivas permitindo nulos

Revision ID: 3ade4b4e28d4
Revises: a82ba19633a9
Create Date: 2026-04-21 18:58:47.335716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ade4b4e28d4'
down_revision: Union[str, Sequence[str], None] = 'a82ba19633a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
