"""Criacao das tabelas  permitindo nulos

Revision ID: a82ba19633a9
Revises: 
Create Date: 2026-04-21 18:30:05.628369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82ba19633a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modalidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_modalidade', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_treino_cardio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_modalidade', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('distancia_km', sa.Float(), nullable=True),
    sa.Column('tempo_minutos', sa.Float(), nullable=True),
    sa.Column('pace_medio', sa.String(length=10), nullable=True),
    sa.Column('bpm_medio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_modalidade'], ['modalidade.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_treino_forca',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('exercicio', sa.String(length=100), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('repeticoes', sa.Integer(), nullable=True),
    sa.Column('carga_kg', sa.Float(), nullable=True),
    sa.Column('rir', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_treino_forca')
    op.drop_table('registro_treino_cardio')
    op.drop_table('usuario')
    op.drop_table('modalidade')
    # ### end Alembic commands ###
